# Generated by Django 4.2.8 on 2025-12-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="temperature (°C)"
                    ),
                ),
                (
                    "soil_humidity",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="soil humidity (%)"
                    ),
                ),
                (
                    "light_level",
                    models.PositiveIntegerField(verbose_name="light level (lux)"),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="recorded at"),
                ),
                (
                    "user_plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_data",
                        to="plants.userplant",
                        verbose_name="plant",
                    ),
                ),
            ],
            options={
                "verbose_name": "sensor data",
                "verbose_name_plural": "sensor data",
                "db_table": "sensor_data",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["user_plant", "-recorded_at"],
                        name="sensor_data_user_pl_d1ee4b_idx",
                    )
                ],
            },
        ),
    ]
