# Generated by Django 4.2.8 on 2025-12-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="air_humidity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Air humidity from DHT11 sensor",
                max_digits=5,
                null=True,
                verbose_name="air humidity (%)",
            ),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="soil_humidity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional - only if soil moisture sensor is available",
                max_digits=5,
                null=True,
                verbose_name="soil humidity (%)",
            ),
        ),
    ]
