# Generated by Django 4.2.8 on 2025-12-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlantType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(max_length=100, verbose_name="name (Ukrainian)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="name (English)"),
                ),
                (
                    "scientific_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="scientific name",
                    ),
                ),
                (
                    "watering_frequency_days",
                    models.PositiveIntegerField(
                        verbose_name="watering frequency (days)"
                    ),
                ),
                (
                    "fertilizing_frequency_days",
                    models.PositiveIntegerField(
                        verbose_name="fertilizing frequency (days)"
                    ),
                ),
                (
                    "repotting_frequency_months",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="repotting frequency (months)",
                    ),
                ),
                (
                    "optimal_temp_min",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        verbose_name="optimal temperature min (°C)",
                    ),
                ),
                (
                    "optimal_temp_max",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        verbose_name="optimal temperature max (°C)",
                    ),
                ),
                (
                    "optimal_humidity_min",
                    models.PositiveIntegerField(
                        verbose_name="optimal humidity min (%)"
                    ),
                ),
                (
                    "optimal_humidity_max",
                    models.PositiveIntegerField(
                        verbose_name="optimal humidity max (%)"
                    ),
                ),
                (
                    "optimal_light_min",
                    models.PositiveIntegerField(verbose_name="optimal light min (lux)"),
                ),
                (
                    "optimal_light_max",
                    models.PositiveIntegerField(verbose_name="optimal light max (lux)"),
                ),
                (
                    "description_uk",
                    models.TextField(verbose_name="description (Ukrainian)"),
                ),
                (
                    "description_en",
                    models.TextField(verbose_name="description (English)"),
                ),
                (
                    "care_tips_uk",
                    models.TextField(
                        blank=True, null=True, verbose_name="care tips (Ukrainian)"
                    ),
                ),
                (
                    "care_tips_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="care tips (English)"
                    ),
                ),
                (
                    "is_custom",
                    models.BooleanField(default=False, verbose_name="custom plant"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "plant type",
                "verbose_name_plural": "plant types",
                "db_table": "plant_types",
                "ordering": ["name_en"],
            },
        ),
    ]
