# Generated by Django 4.2.8 on 2025-12-11 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plant_types", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="planttype",
            name="created_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_plant_types",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
    ]
