# Generated by Django 4.2.8 on 2025-12-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CareLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateField(verbose_name="scheduled date")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("watering", "Watering"),
                            ("fertilizing", "Fertilizing"),
                            ("repotting", "Repotting"),
                        ],
                        max_length=12,
                        verbose_name="task type",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="completed"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                ("skipped", models.BooleanField(default=False, verbose_name="skipped")),
                (
                    "auto_adjusted",
                    models.BooleanField(
                        default=False, verbose_name="auto adjusted by sensor"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "care log",
                "verbose_name_plural": "care logs",
                "db_table": "care_logs",
                "ordering": ["scheduled_date", "-created_at"],
            },
        ),
    ]
