# Generated by Django 4.2.8 on 2025-12-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("care", "0001_initial"),
        ("plants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carelog",
            name="user_plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="care_logs",
                to="plants.userplant",
                verbose_name="plant",
            ),
        ),
        migrations.AddIndex(
            model_name="carelog",
            index=models.Index(
                fields=["user_plant", "scheduled_date"],
                name="care_logs_user_pl_ebd9a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carelog",
            index=models.Index(
                fields=["scheduled_date", "is_completed"],
                name="care_logs_schedul_94bae3_idx",
            ),
        ),
    ]
