# Generated by Django 4.2.8 on 2025-12-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plant_types", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPlant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_name",
                    models.CharField(max_length=100, verbose_name="custom name"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="location"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="plant_photos/",
                        verbose_name="photo",
                    ),
                ),
                ("last_watered_date", models.DateField(verbose_name="last watered")),
                (
                    "last_fertilized_date",
                    models.DateField(verbose_name="last fertilized"),
                ),
                (
                    "last_repotted_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="last repotted"
                    ),
                ),
                ("next_watering_date", models.DateField(verbose_name="next watering")),
                (
                    "next_fertilizing_date",
                    models.DateField(verbose_name="next fertilizing"),
                ),
                (
                    "next_repotting_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="next repotting"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("warning", "Needs Attention"),
                            ("critical", "Critical"),
                        ],
                        default="healthy",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "has_sensor",
                    models.BooleanField(default=False, verbose_name="has sensor"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "plant_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_plants",
                        to="plant_types.planttype",
                        verbose_name="plant type",
                    ),
                ),
            ],
            options={
                "verbose_name": "user plant",
                "verbose_name_plural": "user plants",
                "db_table": "user_plants",
                "ordering": ["-created_at"],
            },
        ),
    ]
